#!/bin/sh

set -u

case ${HOME:-} in
  /*) ;;
  *)
    printf '%s\n' 'dotfiles: HOME must be an absolute path' >&2
    exit 1
    ;;
esac

if [ ! -d "$HOME/.cfg" ]; then
  printf '%s\n' "dotfiles: repository metadata not found at $HOME/.cfg" >&2
  exit 1
fi

exec git --git-dir="$HOME/.cfg" --work-tree="$HOME" "$@"
