bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Prefix 
unbind C-Space 
set -g prefix C-Space
bind C-Space send-prefix

# Mouse support
set -g mouse on

set-option -g history-limit 5000

set -g extended-keys on

# First window and panes starts 1
set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on # Renumber windows when deleting

# Default layout
set-hook -g after-split-window 'if-shell "[[ $(tmux list-panes -F \"#P\" | wc -l) -ge 2 ]]" "select-layout -E main-vertical"'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Statusline
set -g focus-events on
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 99
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right-length 99
set -g status-justify absolute-centre

set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0

# Restore tmux env after system restart
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'M-s'
set -g @resurrect-restore 'M-S'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-dir ~/.config/tmux/resurrect

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Fuzzy find
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-f"
TMUX_FZF_OPTIONS="-p -w 80% -h 80% -m --layout=reverse --inline-info"
# Neovim 
set -g mode-keys vi
set -g @plugin 'aserowy/tmux.nvim'

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

# Navigation 
set -g @tmux-nvim-navigation true
set -g @tmux-nvim-navigation-cycle false
set -g @tmux-nvim-navigation-keybinding-left 'M-h'
set -g @tmux-nvim-navigation-keybinding-down 'M-j'
set -g @tmux-nvim-navigation-keybinding-up 'M-k'
set -g @tmux-nvim-navigation-keybinding-right 'M-l'

bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

unbind \%
bind-key -n M-\\ split-window -h -c '#{pane_current_path}'
unbind \"
bind-key -n M-| split-window -v -c '#{pane_current_path}'

bind-key -n M-f resize-pane -Z

bind-key -n M-q kill-pane
bind-key -n M-Q confirm kill-window

unbind c
bind-key -n M-n command-prompt -p "Window name:" "new-window -c '#{pane_current_path}' -n '%%'"
bind-key -n M-N \
  command-prompt -p "Session name:,Root dir:" -I ",#{pane_current_path}" "run-shell '/home/ruohao/.config/tmux/scripts/new-session-template.sh %1 %2"

bind-key -n M-r command-prompt -I "#W" { rename-window "%%" }
bind-key -n M-R command-prompt -I "#S" { rename-session "%%" }

# resize
set -g @tmux-nvim-resize true
set -g @tmux-nvim-resize-step-x 1
set -g @tmux-nvim-resize-step-y 1
set -g @tmux-nvim-resize-keybinding-left 'C-h'
set -g @tmux-nvim-resize-keybinding-down 'C-j'
set -g @tmux-nvim-resize-keybinding-up 'C-k'
set -g @tmux-nvim-resize-keybinding-right 'C-l'

# yank
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @custom_copy_command 'wl-clipboard'
set -g @shell_mode 'vi'

# open
set -g @plugin 'tmux-plugins/tmux-open'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
